package com.codenameone.kotlinexample

import com.codename1.system.Lifecycle
import com.codename1.ui.Button
import com.codename1.ui.Dialog
import com.codename1.ui.FontImage
import com.codename1.ui.Form
import com.codename1.ui.events.ActionEvent
import com.codename1.ui.layouts.BoxLayout

/**
 * This file was generated by [Codename One initializr](https://start.codenameone.com/) for the purpose
 * of building native mobile applications using Java and Kotlin.
 */
open class ExampleKotlinApp : Lifecycle() {
    override fun runApp() {
        val hi = Form("Hi World", BoxLayout.y())
        val helloButton = Button("Hello World")
        hi.add(helloButton)
        helloButton.addActionListener { e: ActionEvent? -> hello() }
        hi.toolbar.addMaterialCommandToSideMenu("Hello Command",
                FontImage.MATERIAL_CHECK, 4f) { e: ActionEvent? -> hello() }
        hi.show()
    }

    private fun hello() {
        Dialog.show("Hello Codename One", "Welcome to Codename One", "OK", null)
    }
}